# -*- coding: utf-8 -*-
"""scalable_CNF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/SchulzKilian/flow_matching/blob/main/examples/2d_riemannian_flow_matching_sphere.ipynb

# A fisher flow matching example for text
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/facebookresearch/flow_matching.git
# %cd flow_matching

# Commented out IPython magic to ensure Python compatibility.
# %cd flow_matching
# %git pull

!pip install -e .

"""## Imports and init device"""

# Commented out IPython magic to ensure Python compatibility.
# %ls

import time
import torch
import math
import numpy as np
import sys
import os
from torch import nn, Tensor
import torch.nn.functional as F
import sys
import os


text_path = os.path.abspath("examples/text")

if text_path not in sys.path:
    sys.path.append(text_path)



# flow_matching
from examples.text.model.transformer import Transformer
# from examples.text.data import DataState
from examples.text.data.data import get_data_state, get_data_loaders
from flow_matching.path import GeodesicProbPath
from flow_matching.path.scheduler import CondOTScheduler
from flow_matching.solver import ODESolver, RiemannianODESolver
from flow_matching.utils import ModelWrapper
from flow_matching.utils.manifolds import Sphere, Manifold


# visualization
import matplotlib.pyplot as plt
from omegaconf import OmegaConf

from matplotlib import cm

if torch.cuda.is_available():
    device = 'cuda:0'
    print('Using gpu')
else:
    device = 'cpu'
    print('Using cpu.')

torch.manual_seed(42)

"""## Dataset"""

def inf_train_gen(batch_size: int = 200, device: str = "cpu"):
    x1 = torch.rand(batch_size, device=device) * 4 - 2
    x2_ = (torch.rand(batch_size, device=device) - torch.randint(high=2, size=(batch_size, ), device=device) * 2)
    x2 = x2_ + (torch.floor(x1) % 2)

    data = torch.cat([x1[:, None], x2[:, None]], dim=1)

    return data.float()

def wrap(manifold, samples):
    center = torch.cat([torch.zeros_like(samples), torch.ones_like(samples[..., 0:1])], dim=-1)
    samples = torch.cat([samples, torch.zeros_like(samples[..., 0:1])], dim=-1) / 2

    return manifold.expmap(center, samples)

"""## Model"""

conf = OmegaConf.create({
    # --- Model Params (Used by transformer.py) ---
    "hidden_size": 384,
    "n_heads": 6,
    "cond_dim": 64,          # Dimension for time embeddings
    "dropout": 0.1,
    "n_blocks": 4,
    "model": { "length": 64 }, # Sequence Length (keep small for testing)

    # --- Data Params (Used by data.py) ---
    "data": {
        "train": "wikitext103",
        "valid": "wikitext103",
        "cache_dir": "./data_cache",
        "num_workers": 2
    },
    "training": { "batch_size": 32 },
    "compute": { "ngpus": 1 },
    "eval": { "batch_size": 32 }
})

# Parameters derived from config
seq_len = conf.model.length
vocab_size = 50304 # We will clip real data to this size for this demo
dim = seq_len * vocab_size # Total dimension of the flattened sphere vector

class ProjectToTangent(nn.Module):
    """Projects a vector field onto the tangent plane at the input."""

    def __init__(self, vecfield: nn.Module, manifold: Manifold):
        super().__init__()
        self.vecfield = vecfield
        self.manifold = manifold

    def forward(self, x: Tensor, t: Tensor) -> Tensor:
        x = self.manifold.projx(x)
        v = self.vecfield(x, t)
        v = self.manifold.proju(x, v)
        return v

class FlowMatchingTransformer(Transformer):
    def __init__(self, vocab_size, masked, config):
        # Initialize the original Transformer
        super().__init__(vocab_size, masked, config)

        # 1. OVERWRITE the embedding layer
        # Original was nn.Embedding (Integers -> Vector)
        # We need nn.Linear (Sphere Vector -> Vector)
        self.vocab_embed = nn.Linear(vocab_size, config.hidden_size)
        self.expected_flat_dim = config.model.length * vocab_size

    def forward(self, x, t):
      # 1. FIX TIME SHAPE: Ensure t is (Batch,), not (Batch, 1)
      if t.ndim > 1:
          t = t.squeeze()

      # 2. FIX DATA SHAPE: Strip appended time column if present
      if x.shape[-1] == self.expected_flat_dim + 1:
          x = x[:, :-1]

      # 3. Reshape x to Sequence: (Batch, SeqLen, Vocab)
      b_size = x.shape[0]
      x_reshaped = x.view(b_size, self.config.model.length, self.vocab_size)

      # 4. Run Transformer
      out = super().forward(x_reshaped, t)

      # 5. Flatten output
      return out.view(b_size, -1)

# --- ASSERTION: Verify Model Input/Output ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
test_model = FlowMatchingTransformer(vocab_size, False, conf).to(device)
test_input = torch.randn(32, dim).to(device) # Batch 32, Flat Dimension
test_time = torch.rand(32).to(device)

with torch.no_grad():
    test_out = test_model(test_input, test_time)

assert test_out.shape == test_input.shape, f"Shape mismatch! Expected {test_input.shape}, got {test_out.shape}"
print("✅ Model Wrapper is working. Input/Output shapes align.")



"""**Data Setup**"""

import torch.distributed as dist

# Running on a fake distributed system
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "12355" # Any free port

# 'gloo' works on both CPU and GPU and is safer for notebooks.
# rank=0 means "I am the main process".
# world_size=1 means "There is only 1 GPU total".
if not dist.is_initialized():
    dist.init_process_group(backend="gloo", rank=0, world_size=1)

data_state = get_data_state(conf)
train_loader, _ = get_data_loaders(conf, data_state)
train_iter = iter(train_loader)

def get_text_batch(iterator, loader, vocab_size):
    """Helper to get next batch and convert Ints -> Sphere Vectors"""
    try:
        batch = next(iterator)
    except StopIteration:
        iterator = iter(loader)
        batch = next(iterator)

    # Get Integers
    ids = batch['input_ids'].to(device)
    # ids = torch.clamp(ids, 0, vocab_size - 1)

    # Convert to One-Hot Floats (The Fisher/Sphere projection)
    x = F.one_hot(ids, num_classes=vocab_size).float()

    # Flatten to (Batch, Dim) so it looks like a simple vector to the Solver
    return x.view(x.shape[0], -1), iterator

def wrap(manifold, samples):
    center = torch.cat([torch.zeros_like(samples), torch.ones_like(samples[..., 0:1])], dim=-1)
    samples = torch.cat([samples, torch.zeros_like(samples[..., 0:1])], dim=-1) / 2

    return manifold.expmap(center, samples)

print("Data loading finished successfully")

"""## Train Velocity Flow Matching model"""

# training arguments
lr = 1e-4
batch_size = 4096
iterations = 5001
print_every = 100
manifold = Sphere()

# velocity field model init
vf = ProjectToTangent(  # Ensures we can just use Euclidean divergence.
    FlowMatchingTransformer(  # Vector field in the ambient space.
        vocab_size=vocab_size,
        masked=False,
        config=conf
    ),
    manifold=manifold,
)
vf.to(device)

# instantiate an affine path object
path = GeodesicProbPath(scheduler=CondOTScheduler(), manifold=manifold)

# init optimizer
optim = torch.optim.Adam(vf.parameters(), lr=lr)

# train
start_time = time.time()
vf.train()
for i in range(iterations):
    optim.zero_grad()

    # sample data (user's responsibility): in this case, (X_0,X_1) ~ pi(X_0,X_1) = N(X_0|0,I)q(X_1)
    x_1, train_iter = get_text_batch(train_iter, train_loader, vocab_size)
    x_0 = torch.randn_like(x_1).to(device)

    # x_1 = wrap(manifold, x_1)
    # x_0 = wrap(manifold, x_0)

    x_1 = x_1 / x_1.norm(dim=-1, keepdim=True)

    # x_0 is the Noise.
    # Gaussian noise usually has norm sqrt(dim). We must normalize it too.
    x_0 = torch.randn_like(x_1)
    x_0 = x_0 / x_0.norm(dim=-1, keepdim=True)

    # sample time (user's responsibility)
    t = torch.rand(x_1.shape[0]).to(device)

    # sample probability path
    path_sample = path.sample(t=t, x_0=x_0, x_1=x_1)
    pred_v = vf(path_sample.x_t, path_sample.t)

    # flow matching l2 loss
    loss = torch.pow(pred_v - path_sample.dx_t, 2).sum()

    # optimizer step
    loss.backward() # backward
    optim.step() # update

    # log loss
    if (i+1) % print_every == 0:
        elapsed = time.time() - start_time
        target_magnitude = path_sample.dx_t.abs().mean().item()

        print('| iter {:6d} | {:5.2f} ms/step | loss {:8.3f} '
              .format(i+1, elapsed*1000/print_every, loss.item()))
        start_time = time.time()

"""#### Sample from trained model"""

class WrappedModel(ModelWrapper):
    def forward(self, x: torch.Tensor, t: torch.Tensor, **extras):
        return self.model(x=x, t=t)

wrapped_vf = WrappedModel(vf)

# --- 1. Setup & Noise ---
# We define the dimensions explicitly to avoid confusion
target_seq_len = conf.model.length
target_vocab = vocab_size
flat_dim = target_seq_len * target_vocab

# We attempt to generate 5 samples
desired_batch_size = 5

# Generate Noise on Unit Sphere
# Shape: (5, 64000)
x_init = torch.randn((desired_batch_size, flat_dim), dtype=torch.float32, device=device)
x_init = x_init / x_init.norm(dim=-1, keepdim=True)

# --- 2. Inference Wrapper (Fixes Time Broadcasting) ---
def inference_model(t, x):
    # The solver passes 't' as a scalar (0-dim).
    # The Transformer needs 't' as a vector (Batch-dim).
    if t.ndim == 0:
        # Create vector [t, t, t, ...] matching x's batch size
        t = torch.full((x.shape[0],), t.item(), device=x.device)

    # Forward pass: Model expects (x, t)
    return vf(x, t)

# --- 3. Run ODE Solver ---
step_size = 0.05
N = 20

solver = RiemannianODESolver(velocity_model=inference_model, manifold=manifold)

print(f"Generating {desired_batch_size} samples...")
sol = solver.sample(
    x_init=x_init,
    step_size=step_size,
    method="euler",
    return_intermediates=False,
    time_grid=torch.linspace(0, 1, N).to(device),
    verbose=True,
)

# --- 4. Dynamic Decoding (Fixes Shape Error) ---
final_x = sol[-1] # Get the final state

# Calculate how many full sentences exist in the output
# This prevents crashes if the batch dimension was squeezed or altered
total_elements = final_x.numel()
sentence_size = flat_dim

actual_batch_size = total_elements // sentence_size

print(f"DEBUG: Output Elements: {total_elements}")
print(f"DEBUG: Reshaping to Batch Size: {actual_batch_size}")

if actual_batch_size == 0:
    raise ValueError(f"Output size {total_elements} is smaller than a single sentence ({sentence_size})!")

# Reshape safely: (Batch, SeqLen, Vocab)
final_x = final_x.view(actual_batch_size, target_seq_len, target_vocab)

# --- 5. Convert to Text ---
# Inverse Fisher Transform: Probabilities = x^2
probs = torch.square(final_x)
predicted_ids = probs.argmax(dim=-1)

# Decode
from transformers import GPT2TokenizerFast
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

print("\n--- Generated Samples ---")
for i, sent_ids in enumerate(predicted_ids):
    text = tokenizer.decode(sent_ids, skip_special_tokens=True)
    print(f"Sample {i+1}: {text}\n")

"""### Visualize the path"""

